In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
""" 
seismicity_dependent csv file had 14,127 lines with extra commas in it which 
had to be removed
"""

temp_probe = gpd.read_file("2m_temperature_probe_INGENIOUS_regional_data/2m_temperature_probe_n83geo/2m_temperature_probe_n83geo.shp")
faults_quarternary = gpd.read_file("faults_quaternary_INGENIOUS_regional_data/faults_quaternary_regional.shp")
geodetics = pd.read_csv("geodetics_INGENIOUS_regional_data/geodetic_strain_rate_csv.csv")
great_basin_flows = gpd.read_file("great_basin_q_volcanics/great_basin_flows.shp")
great_basin_vents = gpd.read_file("great_basin_q_volcanics/great_basin_vents.shp")
paleo_geothermal = gpd.read_file("paleo_geothermal_regional/Paleo_geothermal_final.shp")
qfaults = gpd.read_file("qfaults_ingenious_nad83conus117_2023-06-27/qfaults_ingenious_nad83conus117_2023-06-27.shp")
seismicity_dependent = pd.read_csv("seismicity_INGENIOUS_regional_data/dependent_eq/dependent_eq_rate_density_wgs84_csv.csv")
seismicity_independent = pd.read_csv("seismicity_INGENIOUS_regional_data/independent_eq/independent_eq_rate_density_wgs84_csv.csv")
study_area_boundary = gpd.read_file("study_area_boundary_INGENIOUS_regional_data_bp1/GB_study_area_NAD83.shp")
# wellspring = ??????????????, not sure which type of file to read

# Temp Probe

In [22]:
temp_probe.head()

,OBJECTID,Station,Area,County,State,UTM_E,UTM_N,T1m,T15m,T2m,...,Date_6,T1m_7,T15m_7,T2m_7,Date_7,Org_Stn,Link,LatDegreeN,LongDegree,geometry
0,1,DQ001,Desert Queen,Churchill,NV,340729,4408444,NaN,NaN,23.1,...,NaT,NaN,NaN,0.0,NaT,Q01,NaN,39.811067,-118.860703,POINT (-118.8607 39.81107)
1,2,DQ002,Desert Queen,Churchill,NV,341657,4406765,NaN,NaN,30.5,...,2008-10-27,NaN,NaN,25.7,2008-12-10,Q02,NaN,39.796120,-118.849461,POINT (-118.84946 39.79612)
2,3,DQ003,Desert Queen,Churchill,NV,341181,4405689,NaN,NaN,28.7,...,NaT,NaN,NaN,0.0,NaT,Q03,NaN,39.786342,-118.854758,POINT (-118.85476 39.78634)
3,4,DQ004,Desert Queen,Churchill,NV,340674,4405731,NaN,NaN,29.2,...,NaT,NaN,NaN,0.0,NaT,Q04,NaN,39.786625,-118.860686,POINT (-118.86069 39.78663)
4,5,DQ005,Desert Queen,Churchill,NV,338490,4405115,NaN,NaN,24.3,...,NaT,NaN,NaN,0.0,NaT,Q05,NaN,39.780666,-118.886028,POINT (-118.88603 39.78067)

In [23]:
temp_probe.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 3800 entries, 0 to 3799
Data columns (total 47 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OBJECTID    3800 non-null   int64
 1   Station     3800 non-null   str
 2   Area        3800 non-null   str
 3   County      3800 non-null   str
 4   State       3800 non-null   str
 5   UTM_E       3800 non-null   int64
 6   UTM_N       3800 non-null   int64
 7   T1m         1573 non-null   str
 8   T15m        1723 non-null   str
 9   T2m         3800 non-null   float64
 10  F2mDAB      3800 non-null   float64
 11  Date        3800 non-null   datetime64[ms]
 12  Note        3800 non-null   str
 13  Project     586 non-null    str
 14  Organizati  3800 non-null   str
 15  Contact     3654 non-null   str
 16  Citation    2662 non-null   str
 17  Notes       170 non-null    str
 18  T1m_2       108 non-null    str
 19  T15m_2      108 non-null    str
 20  T2m_2       3800 non-null   float64
 21  Date_2      143 non-null    datetime64[ms]
 22  T1m_3       84 non-null     str
 23  T15m_3      84 non-null     str
 24  T2m_3       3800 non-null   float64
 25  Date_3      103 non-null    datetime64[ms]
 26  T1m_4       69 non-null     str
 27  T15m_4      69 non-null     str
 28  T2m_4       3800 non-null   float64
 29  Date_4      87 non-null     datetime64[ms]
 30  T1m_5       65 non-null     str
 31  T15m_5      65 non-null     str
 32  T2m_5       3800 non-null   float64
 33  Date_5      76 non-null     datetime64[ms]
 34  T1m_6       4 non-null      str
 35  T15m_6      4 non-null      str
 36  T2m_6       3800 non-null   float64
 37  Date_6      14 non-null     datetime64[ms]
 38  T1m_7       1 non-null      str
 39  T15m_7      63 non-null     str
 40  T2m_7       3800 non-null   float64
 41  Date_7      9 non-null      datetime64[ms]
 42  Org_Stn     2744 non-null   str
 43  Link        192 non-null    str
 44  LatDegreeN  3800 non-null   float64
 45  LongDegree  3800 non-null   float64
 46  geometry    3800 non-null   geometry
dtypes: datetime64[ms](7), float64(10), geometry(1), int64(3), str(26)
memory usage: 1.4 MB

# Faults Quarternary

In [24]:
faults_quarternary.head()

,NAME,SLIPRATE_N,RECENCY_N,CODE,NUM,AGE,ACODE,SLIPCODE,SLIPDIRECT,FCODE,...,SLIPRTmmyr,Comments,Geometry_C,Notes,SlipRate_c,Recency_ci,DIPDIRECT,FTYPE_,SLIPSENSE,geometry
0,"Abert Rim fault, Lake Abert section",0.52,"<15,000",123,829a,"<15,000",2,3,NaN,1,...,0.2-1,NaN,NaN,NaN,NaN,NaN,NW,Well Constrained,N,"MULTILINESTRING ((-120.06298 42.76393, -120.06..."
1,"Abert Rim fault, Lake Abert section",0.52,"<15,000",133,829a,"<130,000",3,3,NaN,1,...,0.2-1,NaN,NaN,NaN,NaN,NaN,NW,Well Constrained,N,"LINESTRING (-120.2395 42.45413, -120.23958 42...."
2,"Abert Rim fault, Northern section",0.06,"<1,600,000",154,829b,"<1,600,000",5,4,NaN,1,...,<0.2,NaN,NaN,NaN,NaN,NaN,NW,Well Constrained,N,"MULTILINESTRING ((-119.9517 43.03091, -119.952..."
3,Adobe Range fault,0.01,"<1,600,000",254,1561,"<1,600,000",5,4,NaN,2,...,<0.2,NaN,NaN,NaN,NaN,NaN,NW,Moderately Constrained,N,"MULTILINESTRING ((-115.71997 41.17601, -115.72..."
4,Agai Pah Hills fault zone,0.195,"<1,600,000",134,1308,"<130,000",3,4,NaN,1,...,<0.2,NaN,NaN,NaN,NaN,NaN,Unspecified,Well Constrained,RL,"MULTILINESTRING ((-118.6114 38.8572, -118.6109..."

In [25]:
faults_quarternary.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 22118 entries, 0 to 22117
Data columns (total 23 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   NAME        22016 non-null  str
 1   SLIPRATE_N  20633 non-null  str
 2   RECENCY_N   20594 non-null  str
 3   CODE        22118 non-null  int64
 4   NUM         18508 non-null  str
 5   AGE         21748 non-null  str
 6   ACODE       22118 non-null  int64
 7   SLIPCODE    22118 non-null  int64
 8   SLIPDIRECT  4 non-null      str
 9   FCODE       22118 non-null  int64
 10  MAPPEDSCAL  18020 non-null  str
 11  SECONDARYS  89 non-null     str
 12  CFM_URL     2304 non-null   str
 13  SLIPRTmmyr  19427 non-null  str
 14  Comments    900 non-null    str
 15  Geometry_C  14389 non-null  str
 16  Notes       2 non-null      str
 17  SlipRate_c  17849 non-null  str
 18  Recency_ci  15485 non-null  str
 19  DIPDIRECT   18242 non-null  str
 20  FTYPE_      21670 non-null  str
 21  SLIPSENSE   18885 non-null  str
 22  geometry    22118 non-null  geometry
dtypes: geometry(1), int64(4), str(18)
memory usage: 3.9 MB

# Geodetics

In [26]:
geodetics.head()

,long_wgs84,lat_wgs84,second_inv_strainrate_10e-9,dilationrate_10e-9,shearrate_10e-9
0,-111.086533,43.023580,6.9,0.7,4.5
1,-111.080377,43.023302,6.8,0.6,4.5
2,-111.074220,43.023023,6.8,0.6,4.5
3,-111.068064,43.022744,6.8,0.6,4.5
4,-111.061908,43.022465,6.7,0.6,4.5

In [27]:
geodetics.info()

<class 'pandas.DataFrame'>
RangeIndex: 1996714 entries, 0 to 1996713
Data columns (total 5 columns):
 #   Column                       Dtype
---  ------                       -----
 0   long_wgs84                   float64
 1   lat_wgs84                    float64
 2   second_inv_strainrate_10e-9  float64
 3   dilationrate_10e-9           float64
 4   shearrate_10e-9              float64
dtypes: float64(5)
memory usage: 76.2 MB

# Great Basin Flows

In [28]:
great_basin_flows.head()

,Flow_Name,Rock_Type,Age,SHAPE_Leng,SHAPE_Area,Source,Rock_Comp,State,Age_Source,Geo_Age,AREA,PERIMETER,descriptio,AgeSource,Map_Symbol,geometry
0,Buffalo Valley,Basalt,0.95 Ma,0.0,0.0,ESRI/Googel Earth Imagery,mafic,NV,NaN,NaN,0.0,0.0,NaN,NaN,NaN,"POLYGON ((-117.31661 40.32046, -117.31809 40.3..."
1,Buffalo Valley,Basalt,1.24 Ma,0.0,0.0,ESRI/Googel Earth Imagery,mafic,NV,NaN,NaN,0.0,0.0,NaN,NaN,NaN,"POLYGON ((-117.28678 40.3523, -117.28794 40.35..."
2,Buffalo Valley,Basalt,0.95-1.2 Ma,0.0,0.0,ESRI/Googel Earth Imagery,mafic,NV,NaN,NaN,0.0,0.0,NaN,NaN,NaN,"POLYGON ((-117.26184 40.36934, -117.2623 40.36..."
3,Buffalo Valley,Basalt,1.14 Ma,0.0,0.0,ESRI/Googel Earth Imagery,mafic,NV,NaN,NaN,0.0,0.0,NaN,NaN,NaN,"POLYGON ((-117.27527 40.39087, -117.27531 40.3..."
4,Buffalo Valley,Basalt,0.95-1.2 Ma,0.0,0.0,ESRI/Googel Earth Imagery,mafic,NV,NaN,NaN,0.0,0.0,NaN,NaN,NaN,"POLYGON ((-117.2481 40.37832, -117.24805 40.37..."

In [29]:
great_basin_flows.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 5281 entries, 0 to 5280
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Flow_Name   2667 non-null   str
 1   Rock_Type   1568 non-null   str
 2   Age         3913 non-null   str
 3   SHAPE_Leng  5281 non-null   float64
 4   SHAPE_Area  5281 non-null   float64
 5   Source      5281 non-null   str
 6   Rock_Comp   5281 non-null   str
 7   State       5281 non-null   str
 8   Age_Source  908 non-null    str
 9   Geo_Age     1374 non-null   str
 10  AREA        5281 non-null   float64
 11  PERIMETER   5281 non-null   float64
 12  descriptio  582 non-null    str
 13  AgeSource   127 non-null    str
 14  Map_Symbol  3720 non-null   str
 15  geometry    5281 non-null   geometry
dtypes: float64(4), geometry(1), str(11)
memory usage: 660.3 KB

# Great Basin Vents

In [30]:
great_basin_vents.head()

,Rock_Comp,Age,State,Rock_Type,Age_Source,Source,Geo_Age,Type,AREA,PERIMETER,Name,Descriptio,Map_Symbol,Lat,Long,geometry
0,mafic,0.95 to 1.24 Ma,NV,Basalt,NaN,Buffalo Valley,NaN,NaN,0.0,0.0,NaN,NaN,NaN,40.365571,-117.273411,POINT Z (-117.27341 40.36557 0)
1,mafic,0.95 to 1.24 Ma,NV,Basalt,NaN,Buffalo Valley,NaN,NaN,0.0,0.0,NaN,NaN,NaN,40.368904,-117.266369,POINT Z (-117.26637 40.3689 0)
2,mafic,0.95 to 1.24 Ma,NV,Basalt,NaN,Buffalo Valley,NaN,NaN,0.0,0.0,NaN,NaN,NaN,40.380596,-117.245219,POINT Z (-117.24522 40.3806 0)
3,mafic,1.14 Ma,NV,Basalt,NaN,Buffalo Valley,NaN,NaN,0.0,0.0,NaN,NaN,NaN,40.393598,-117.271517,POINT Z (-117.27152 40.3936 0)
4,mafic,0.95 to 1.24 Ma,NV,Basalt,NaN,Buffalo Valley,NaN,NaN,0.0,0.0,NaN,NaN,NaN,40.346549,-117.265775,POINT Z (-117.26578 40.34655 0)

In [31]:
great_basin_vents.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1514 entries, 0 to 1513
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Rock_Comp   1514 non-null   str
 1   Age         714 non-null    str
 2   State       1514 non-null   str
 3   Rock_Type   306 non-null    str
 4   Age_Source  282 non-null    str
 5   Source      1514 non-null   str
 6   Geo_Age     345 non-null    str
 7   Type        753 non-null    str
 8   AREA        1514 non-null   float64
 9   PERIMETER   1514 non-null   float64
 10  Name        395 non-null    str
 11  Descriptio  496 non-null    str
 12  Map_Symbol  302 non-null    str
 13  Lat         1514 non-null   float64
 14  Long        1514 non-null   float64
 15  geometry    1514 non-null   geometry
dtypes: float64(4), geometry(1), str(11)
memory usage: 189.4 KB

# Paleo Geothermal

In [32]:
paleo_geothermal.head()

,FID_,Long_deg,Lat_deg,Location,State,Deposit_ty,Map_unit,Ref_source,Comments,geometry
0,1,-115.868206,38.365216,Abel Springs,NV,Travertine,Qt,Ayling_2020,NaN,POINT (-115.86821 38.36522)
1,2,-112.004452,43.035922,Alkali Flats Warm Springs,ID,Travertine,Sedimentary rocks (Permian and Pennsylvanian),"Ross, 1971",IGS mapped spring. Digitized travertine in vic...,POINT (-112.00445 43.03592)
2,3,-117.338219,37.825604,Alkali Hot Spring,NV,Travertine,Qt,Ball_1901;Albers and Stewart_1972,NaN,POINT (-117.33822 37.8256)
3,4,-117.337020,37.824204,Alkali Hot Spring,NV,Sinter,Qssi,Faulds_2020,Silica sinter and sulfur stains (sample collec...,POINT (-117.33702 37.8242)
4,5,-117.338159,37.824778,Alkali Hot Spring,NV,Travertine,Qt,Faulds_2020,Mound slightly elongate to NNE (70 x 50 m),POINT (-117.33816 37.82478)

In [33]:
paleo_geothermal.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 709 entries, 0 to 708
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FID_        709 non-null    int64
 1   Long_deg    709 non-null    float64
 2   Lat_deg     709 non-null    float64
 3   Location    709 non-null    str
 4   State       709 non-null    str
 5   Deposit_ty  709 non-null    str
 6   Map_unit    596 non-null    str
 7   Ref_source  708 non-null    str
 8   Comments    537 non-null    str
 9   geometry    709 non-null    geometry
dtypes: float64(2), geometry(1), int64(1), str(6)
memory usage: 55.5 KB

# Qfaults

In [34]:
qfaults.head()

,NAME,NUM,DIPDIRECT,SLIPDIRECT,SLIPSENSE,SECONDARY,SLIPRT2023,SLIPRTNUM,REC2023,RECNUM,...,RCODE2023,SCODE2023,FTYPE_,MAPSCALE,SLIPINFO,RECINFO,COMMENTS,GEOCOMM,Shape_Leng,geometry
0,"Abert Rim fault, Lake Abert section",829a,NW,NaN,N,RL,0.52,0.520,"<15,000",15000,...,2,3,Well Constrained,100,NaN,NaN,NaN,NaN,42725.862911,"MULTILINESTRING ((-249184.043 2200342.64, -249..."
1,"Abert Rim fault, Lake Abert section",829a,NW,NaN,N,LL,0.52,0.520,"<15,000",15000,...,2,3,Well Constrained,100,NaN,NaN,NaN,NaN,4355.039963,"LINESTRING (-264718.747 2166210.239, -264732.8..."
2,"Abert Rim fault, Northern section",829b,NW,NaN,N,LL,0.06,0.060,"<1,600,000",1600000,...,5,4,Well Constrained,100,NaN,NaN,NaN,NaN,33376.945277,"MULTILINESTRING ((-239207.586 2229869.99, -239..."
3,Adobe Range fault,1561,NW,NaN,N,NaN,0.01,0.010,"<1,600,000",1600000,...,5,4,Moderately Constrained,250,NaN,NaN,NaN,NaN,9507.568480,"MULTILINESTRING ((106542.259 2019415.84, 10635..."
4,Agai Pah Hills fault zone,1308,Unspecified,NaN,RL,NaN,0.195,0.195,"<1,600,000",1600000,...,5,4,Well Constrained,250,NaN,NaN,NaN,NaN,5372.664293,"MULTILINESTRING ((-138525.657 1760079.106, -13..."

In [35]:
qfaults.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 22956 entries, 0 to 22955
Data columns (total 22 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   NAME        22956 non-null  str
 1   NUM         19448 non-null  str
 2   DIPDIRECT   18084 non-null  str
 3   SLIPDIRECT  4 non-null      str
 4   SLIPSENSE   19743 non-null  str
 5   SECONDARY   89 non-null     str
 6   SLIPRT2023  22956 non-null  str
 7   SLIPRTNUM   22956 non-null  float64
 8   REC2023     22956 non-null  str
 9   RECNUM      22956 non-null  int64
 10  CODE2023    22956 non-null  int64
 11  FCODE2023   22956 non-null  int64
 12  RCODE2023   22956 non-null  int64
 13  SCODE2023   22956 non-null  int64
 14  FTYPE_      22509 non-null  str
 15  MAPSCALE    18897 non-null  str
 16  SLIPINFO    18855 non-null  str
 17  RECINFO     16442 non-null  str
 18  COMMENTS    905 non-null    str
 19  GEOCOMM     14462 non-null  str
 20  Shape_Leng  22956 non-null  float64
 21  geometry    22956 non-null  geometry
dtypes: float64(2), geometry(1), int64(5), str(14)
memory usage: 3.9 MB

# Seismicity Dependent

In [36]:
seismicity_dependent.head()

,long_wgs84,lat_wgs84,N50_alpha0pt05_10e-12_per_yr_m2,N50_alpha0pt1_10e-12_per_yr_m2,N50_alpha0pt15_10e-12_per_yr_m2,N100_alpha0pt05_10e-12_per_yr_m2,N100_alpha0pt1_10e-12_per_yr_m2,N100_alpha0pt15_10e-12_per_yr_m2,N200_alpha0pt05_10e-12_per_yr_m2,N200_alpha0pt1_10e-12_per_yr_m2,N200_alpha0pt15_10e-12_per_yr_m2
0,-122.00,37.0,940.2,1207.4,1896.3,746.5,1108.5,1396.8,389.3,815.1,868.8
1,-121.95,37.0,1069.0,1141.5,1744.6,837.1,888.8,1437.9,376.1,647.8,986.9
2,-121.90,37.0,1331.6,1818.0,2222.9,1113.4,1520.8,1846.0,650.6,962.8,1400.0
3,-121.85,37.0,1879.6,2770.7,3670.7,1498.8,2314.6,3163.6,1070.1,1641.5,2548.6
4,-121.80,37.0,2087.0,4761.5,6898.4,1965.2,3948.4,6152.4,1973.1,3336.6,4709.8

In [37]:
seismicity_dependent.info()

<class 'pandas.DataFrame'>
RangeIndex: 26741 entries, 0 to 26740
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   long_wgs84                        26741 non-null  float64
 1   lat_wgs84                         26741 non-null  float64
 2   N50_alpha0pt05_10e-12_per_yr_m2   26741 non-null  float64
 3   N50_alpha0pt1_10e-12_per_yr_m2    26741 non-null  float64
 4   N50_alpha0pt15_10e-12_per_yr_m2   26741 non-null  float64
 5   N100_alpha0pt05_10e-12_per_yr_m2  26741 non-null  float64
 6   N100_alpha0pt1_10e-12_per_yr_m2   26741 non-null  float64
 7   N100_alpha0pt15_10e-12_per_yr_m2  26741 non-null  float64
 8   N200_alpha0pt05_10e-12_per_yr_m2  26741 non-null  float64
 9   N200_alpha0pt1_10e-12_per_yr_m2   26741 non-null  float64
 10  N200_alpha0pt15_10e-12_per_yr_m2  26741 non-null  float64
dtypes: float64(11)
memory usage: 2.2 MB

# Seismicity Independent

In [38]:
seismicity_independent.head()

,long_wgs84,lat_wgs84,N50_alpha0pt05_10e-12_per_yr_m2,N50_alpha0pt1_10e-12_per_yr_m2,N50_alpha0pt15_10e-12_per_yr_m2,N100_alpha0pt05_10e-12_per_yr_m2,N100_alpha0pt1_10e-12_per_yr_m2,N100_alpha0pt15_10e-12_per_yr_m2,N200_alpha0pt05_10e-12_per_yr_m2,N200_alpha0pt1_10e-12_per_yr_m2,N200_alpha0pt15_10e-12_per_yr_m2
0,-122.00,37.0,746.6,875.8,1253.8,767.9,1509.3,1461.0,952.5,1519.1,2321.7
1,-121.98,37.0,711.9,889.9,1305.8,714.1,1540.4,1550.2,1147.9,1479.2,2311.6
2,-121.96,37.0,635.2,910.0,1371.0,760.0,1421.0,1642.4,1090.2,1391.6,2303.8
3,-121.94,37.0,600.8,899.7,1438.2,829.1,1366.7,1699.2,1312.3,1551.6,2288.2
4,-121.92,37.0,555.6,898.2,1470.6,871.2,1292.6,1746.2,1432.5,1509.4,2325.0

In [39]:
seismicity_independent.info()

<class 'pandas.DataFrame'>
RangeIndex: 165851 entries, 0 to 165850
Data columns (total 11 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   long_wgs84                        165851 non-null  float64
 1   lat_wgs84                         165851 non-null  float64
 2   N50_alpha0pt05_10e-12_per_yr_m2   165851 non-null  float64
 3   N50_alpha0pt1_10e-12_per_yr_m2    165851 non-null  float64
 4   N50_alpha0pt15_10e-12_per_yr_m2   165851 non-null  float64
 5   N100_alpha0pt05_10e-12_per_yr_m2  165851 non-null  float64
 6   N100_alpha0pt1_10e-12_per_yr_m2   165851 non-null  float64
 7   N100_alpha0pt15_10e-12_per_yr_m2  165851 non-null  float64
 8   N200_alpha0pt05_10e-12_per_yr_m2  165851 non-null  float64
 9   N200_alpha0pt1_10e-12_per_yr_m2   165851 non-null  float64
 10  N200_alpha0pt15_10e-12_per_yr_m2  165851 non-null  float64
dtypes: float64(11)
memory usage: 13.9 MB

# Study Area Boundary

In [40]:
study_area_boundary.head()

,CLASS,AREA,PERIMETER,geometry
0,1,494268.776844,3301.250941,"POLYGON ((-119.25966 37.72854, -119.39199 37.9..."

In [41]:
study_area_boundary.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   CLASS      1 non-null      int64
 1   AREA       1 non-null      float64
 2   PERIMETER  1 non-null      float64
 3   geometry   1 non-null      geometry
dtypes: float64(2), geometry(1), int64(1)
memory usage: 164.0 bytes

# Wellspring

In [42]:
# wellspring.head()